language: erlang
otp_release: 17.5
script:
  - make -j2 test ARCH=xen CONF=dbg
  - make -j2 test ARCH=xen CONF=opt
  - make -j2 test ARCH=xen CONF=lto
  - make -j2 test ARCH=posix CONF=dbg
  - make -j2 test ARCH=posix CONF=opt
  - make -j2 play ARCH=posix CONF=lto
sudo: false
