language: erlang
otp_release: 17.5
script: make; make test && touch .config && make test LING_USE_LTO= && touch .config && make test LING_USE_LTO= LING_DEBUG=1 && touch .config && make test LING_XEN= LING_POSIX=1 && touch .config &&make test LING_XEN= LING_POSIX=1 LING_USE_LTO= && touch .config &&make test LING_XEN= LING_POSIX=1 LING_USE_LTO= LING_DEBUG=1 && make play

