language: erlang
otp_release:
  - 17.5
env:
  - ARCH=xen CONF=dbg
  - ARCH=xen CONF=opt
  - ARCH=xen CONF=lto
  - ARCH=posix CONF=dbg
  - ARCH=posix CONF=opt
  - ARCH=posix CONF=lto
script:
  - make -j2 test ARCH=$ARCH CONF=$CONF
sudo: false
