language: c
os:
  - linux
  - osx
env:
  - ARCH=xen CONF=dbg
  - ARCH=xen CONF=opt
  - ARCH=xen CONF=lto
  - ARCH=posix CONF=dbg
  - ARCH=posix CONF=opt
  - ARCH=posix CONF=lto
before_install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; wget https://s3.amazonaws.com/travis-otp-releases/ubuntu/12.04/erlang-17.5-x86_64.tar.bz2; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; tar xf erlang-17.5-x86_64.tar.bz2 -C ~/otp/; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; source $HOME/otp/17.5/activate; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; brew install erlang; fi
script:
  - make -j2 test ARCH=$ARCH CONF=$CONF
sudo: false
